import "@/app/globals.css";
import type { Metadata } from "next";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: {
    template: "%s - <crescitelli.dev/>",
    default: "Welcome - <crescitelli.dev/>",
  },
  description: "Generated by create next app",
};

interface Props {
  readonly children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="min-h-screen w-full bg-black text-gray-300">
        {children}
      </body>
    </html>
  );
}
