import "@/app/(styles)/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s - crescitelli.dev",
    default: "Welcome - crescitelli.dev",
  },
  description: "Generated by create next app",
};

interface Props {
  readonly children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full">{children}</body>
    </html>
  );
}
