import { Section } from "@/components/Section";
import { Subtitle } from "@/components/Subtitle";
import { Title } from "@/components/Title";
import { WorkCard } from "@/components/workCard/WorkCard";

import { projects } from "@/data/projects";
import { TECH_TAG_QUANTITY_PER_WORK } from "@/lib/constants";

export const metadata = {
  title: "Works",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <main className="max-w-screen min-h-screen lg:mt-5">
      <Section>
        <Title>Explore My Works</Title>
        <Subtitle>
          A selection of projects that reflects my approach to clean design,
          efficient development, and practical problem-solving. Each work
          demonstrates how I turn ideas into functional, purposeful digital
          experiences.
        </Subtitle>
        <div className="mt-15 grid max-[1100px]:grid-cols-1 grid-cols-2 gap-y-20 justify-items-center">
          {projects.map((p) => (
            <WorkCard key={p.id}>
              <WorkCard.Image
                src={`/${p.slug}/preview.png`}
                alt={`Preview image of ${p.name}`}
              />
              <WorkCard.Body>
                <WorkCard.Header tag={p.stack} year={p.date.year} />
                <WorkCard.Title>{p.name}</WorkCard.Title>
                <WorkCard.Description>{p.description}</WorkCard.Description>
                <WorkCard.TagsContainer>
                  {p.technologies.map((tech, i) => {
                    const othersCount =
                      p.technologies.length - TECH_TAG_QUANTITY_PER_WORK;
                    if (i < TECH_TAG_QUANTITY_PER_WORK)
                      return (
                        <WorkCard.TechnologyCard key={tech.name}>
                          {tech.name}
                        </WorkCard.TechnologyCard>
                      );

                    if (i === p.technologies.length - 1)
                      return (
                        <WorkCard.PlusCard
                          key={"others"}
                          quantity={othersCount}
                        />
                      );
                  })}
                </WorkCard.TagsContainer>
                <WorkCard.FeaturesContainer>
                  {p.features.map((f) => (
                    <WorkCard.Feature key={f}>{f}</WorkCard.Feature>
                  ))}
                </WorkCard.FeaturesContainer>
                <WorkCard.Buttons
                  page={p.slug}
                  github={p.github}
                  live={p.live_view}
                />
              </WorkCard.Body>
            </WorkCard>
          ))}
        </div>
      </Section>
    </main>
  );
}
